### ISSUE TITLE
Path issue

### ISSUE THREAD

**Issue by NicolasCARPi** [deepimagej/deepimagej-plugin#3]
Hello,

I'm trying to run this plugin that looks quite interesting, unfortunately the models folder isn't properly recognized. The path is: `/home/user/.opt/Fiji.app//models` instead of `/home/user/.opt/Fiji.app/models`. And no models are recognized (model folders are present).

I tried building the project after modifying [this line](https://github.com/deepimagej/deepimagej-plugin/blob/master/src/DeepImageJ_Explore.java#L54) to remove the extra separator, but I get a Class not found error instead when accessing the plugin in Fiji menu (probably a misstep in the build).

BTW, there are no build instructions, and the build config expects you to have ImageJ/ and Fiji/ in a Desktop/ folder, so I had to comment those line (and copy the files manually after of course). Please add build instructions in the README.

Note : I think it would be best if `dist/` and the final zip file were not committed, as they can be produced from source code, and it's bad practice to track the compiled files (also it makes the repo heavy unnecessarily and clutters the history).

I'm running Archlinux, with Fiji with ImageJ 1.52p Java 1.8.0_66 :)

Cheers,
~Nico

**Comment by carlosuc3m** [comment]
Hello Nicolas,
Which models have you tried to load? If you used the models on the website, the issue is probably that those models are not yet updated to the current version of the plugin (the config file is missing some necessary nodes). The plugin does not allow to load models if the config file is not up to date in order to avoid crashes.
The models in the website will be updated soon. However, if you want, you can try to build the DeepImageJ model using DeepImageJ Build BundledModel plugin and then try to run it.

However, you are right with respect to the issue of the path and it will be changed. Also a more detailed README and installation instructions will be included soon.
The code is under development yet but we expect to have a final version very soon!!

Thank you for your feedback!!

**Comment by NicolasCARPi** [comment]
It was Noise2Void Denoising and I also tried two others just to make sure it wasn't model-dependant.

Now I just tried it again on a different computer and **it works!!!**. What's weird is that the computer is the same setup, with Archlinux, and fiji updated. And the path shows up with two "//" but it's ok apparently. So unless you did a ninja update, I don't know why it wasn't working at home...

Anyway, the path doesn't seem to be the issue at play here :)

Cheers,
~Nico

**Comment by carlosuc3m** [comment]
In principle this issue should not be related to the path but to the config.xml of the models.
I think it now works because the models have been updated in the website. 
Could I ask you to try it again in the first computer and see if it works?
Thank you!

**Comment by NicolasCARPi** [comment]
Yes, will do!

**Comment by NicolasCARPi** [comment]
I can confirm that it now works on both computers, so the issue was with the old models!
