### ISSUE TITLE
Error patch size is too large

### ISSUE THREAD

**Issue by NicolasCARPi** [deepimagej/deepimagej-plugin#5]
I'm trying to run the Noise2Void Denoising model on my images. When selecting the model from the Run menu, the patch size is set to 400 and one cannot modify it.

But when running it, the error is "Patch size is too large (400)".

Why can't I change the patch size and why is it giving me this error?

I tried with 2 channel timelapse, then one channel, then one image, always the same error.

See debug log (no pre or post processing):

DeepImageJ (8.9 us) : Load model: Fully Residual U-net - TEM(fru-net_sev_segmentation)
DeepImageJ (18.4 ms) : Load model error: false
DeepImageJ (18.9 ms) : start progress
DeepImageJ (75.0 ms) : start runner
DeepImageJ (75.4 ms) : call runner
DeepImageJ (76.4 ms) : image size 1756x45
Error patch size is too large 400
DeepImageJ (82.6 ms) : Error, output is null

Cheers,
~Nico

**Comment by carlosuc3m** [comment]
Hello Nico,
The patch size is fixed to 400x400 because the network only admits images of that size because of the way it was programmed.
The plugin does not apply the model to that image because it requires images whose size is at most three times smaller than the patch size.
So this model requires images whose smallest dimension is 134 or more (in your case is 45).
However this limitation might be removed in the near future. 
Thank you again for you feedback!! 

Carlos

**Comment by NicolasCARPi** [comment]
I see. Indeed it would be nice if this limitation could be removed ;)

**Comment by carlosuc3m** [comment]
Hello Nico,
It seems that this limitation is going to be maintained at least for this version.
Regards,
Carlos
